#!/bin/sh

#POST-ACQUISITION SCRIPT TO BE RUN ON SERVER (LINUX)

###########################################################
#USER-DEFINED VARIABLES:

#LOCATION OF ACQUIRED FOLDERS (MOUNTED ON SERVER)


#LOCATION OF META-DATA EXTRACTION FILES FOR RECORDINGS (AFTER POST-ACQUISITION PROCESSING)

###########################################################

#RUN POST-ACQUISITION PROCESSING





#RUN META-DATA EXTRACTION

